#
# How to run:
#  env TEST_WORKERS=5 TEST_DURATION=10 bm ansible play -book database-query-plans-bench.yml
#

---
- name: Run Java tests and create JAR file
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Ensure JDK is installed
      apt:
        name: openjdk-21-jdk
        state: present
      become: yes

    - name: Ensure Maven is installed
      apt:
        name: maven
        state: present
      become: yes

    - name: Compile project and create JAR file
      command: mvn clean package

    - name: Run tests with parameters
      command: |
        mvn test "-DargLine=-ea -Dargs='
        -d {{ lookup('env','DB') | default('postgres', true) }} 
              -U {{ lookup('env','USER_NAME') | default('postgres', true) }}  
              -P {{ lookup('env','USER_PWD') | default('postgres', true) }} 
              -h {{ lookup('env', 'HOST') | default('localhost', true) }}
              -p {{ lookup('env','PORT') | default('5432', true) }} 
              -c {{ lookup('env','TEST_CONCURRENCY') | default('1', true) }} 
              -w {{ lookup('env','TEST_WORKERS') | default('5', true) }} 
              -t {{ lookup('env','TEST_DURATION') | default('10', true) }}
        '"
